import express from 'express';
import {organizationSignup,organizationLogin,fetchOrgDetails,updateOrgInfo,getAllUsers,removeUserDetails,updateUserDetails,organizationLink} from '../controllers/organizationController.js'
import { userSignup } from '../controllers/userController.js';
import protectOrganization from '../middleWare/organizationMiddleware.js'
import protect from '../middleWare/userMiddleWare.js';

const app = express.Router()

app.route('/').post(organizationSignup).get(protectOrganization,getAllUsers)
app.route('/delete-user/:id').delete(protectOrganization,removeUserDetails)
app.route('/update-user/:id').put(protectOrganization,updateUserDetails)
app.route('/add-user').post(protectOrganization,userSignup)
app.route('/login').post(organizationLogin)
app.route('/profile').get(protectOrganization,fetchOrgDetails).put(protectOrganization,updateOrgInfo)
app.route('/join-org').post(organizationLink);

//by organization only and the join org by user but link is generated by organization
//leave org by user
//accept api and history api can be accessed  and update the donation status to complted


export default app

